INSERT INTO images (category_id, url, title, description, detaileddesc, size, medium, slug, year) VALUES
(1, 'https://niybpkzfotwxowffxpps.supabase.co/storage/v1/object/public/artphotos/Beadwork/sfbeadpostcard.jpg', 'Beadings From San Francisco', 'A beaded postcard of the Golden Gate Bridge', 'This beaded postcard of the Golden Gate Bridge was made to honor my time living in my van in San Francisco.', '2" x 4"', 'size 10 and 13 seed beads', 'beadings-from-san-francisco', 2019),
(1, 'https://niybpkzfotwxowffxpps.supabase.co/storage/v1/object/public/artphotos/Beadwork/shiprock.jpg', 'Sunrise at Tsé Bitʼaʼí', 'A beaded postcard of Shiprock', 'This beaded postcard of Shiprock was made to honor my ancestral homeland.', '2" x 4"', 'size 10 and 13 seed beads', 'sunrise-at-tse-bitaí', 2019),
(1, 'https://niybpkzfotwxowffxpps.supabase.co/storage/v1/object/public/artphotos/Beadwork/DiasporUtah.JPG', 'DiasporUtah', 'A beaded "painting" of Utah', 'This piece took 500 hours to create. It represents the spectrum of flora, fauna and cultures within Utah.', '13" x 17"', 'size 10 seed beads', 'diasporutah', 2020),
(1, 'https://niybpkzfotwxowffxpps.supabase.co/storage/v1/object/public/artphotos/Beadwork/vanimalcloseup.jpg', 'Vanimal: The Desert Rose', 'A beaded medallion of my old camper van', 'My old Dodge van which I traveled the western US in', '6" x 6"', 'size 13 seed beads', 'vanimal-the-desert-rose', 2018),
(1, 'https://niybpkzfotwxowffxpps.supabase.co/storage/v1/object/public/artphotos/Beadwork/xmedallion2.JPG', 'X Medallion', 'A beaded medallion for Exene Cervenka of X', 'A beaded medallion commissioned for Exene Cervenka of the punk band, X', '6" x 6"', 'size 13 seed beads', 'x-medallion', 2020),
(1, 'https://niybpkzfotwxowffxpps.supabase.co/storage/v1/object/public/artphotos/Beadwork/medicinewheels2.jpg', 'Medicine Wheels', 'Beaded medicine wheel pins', 'Beaded medicine wheel pins I made for the Urban Indian Center of Salt Lake City. The pins were given to graduates of their substance abuse program.', '1.5" x 1.5"', 'size 13 seed beads', 'medicine-wheels', 2019),
(1, 'https://niybpkzfotwxowffxpps.supabase.co/storage/v1/object/public/artphotos/Beadwork/45rpm.JPG', '45 Revolutions', 'Beaded brooches of 45 RPM adapters', 'These were sold to fundraise for the Native American Music Fund. This organization provides instruments and music lessons to Navajo youth.', '2"x 2"', 'size 13 seed beads', '45-revolutions', 2019),
(1, 'https://niybpkzfotwxowffxpps.supabase.co/storage/v1/object/public/artphotos/Beadwork/floweroflife.jpg', 'Flower of Life', 'A beaded cuff and earring set made for a breast cancer survivor', 'The three flowers represent her, her husband and daughter; a triad of strength and resilience.', 'cuff: 2" x 6", earrings: 1.5" x 1.5"', 'size 13 seed beads', 'flower-of-life', 2019),
(1, 'https://niybpkzfotwxowffxpps.supabase.co/storage/v1/object/public/artphotos/Beadwork/indigenousdissonance1.jpg', 'Indigenous Dissonance', 'A beaded cuff and earring set inspired by black metal and soundwaves', 'Black metal logos, soundwaves and fast paced heartbeats.', 'cuff: 3" x 6", earrings: 1.5" x 1.5"', 'size 13 seed beads', 'indigenous-dissonance', 2019);
