INSERT INTO images (category_id, url, title, description, detaileddesc, size, medium) VALUES
(3, 'https://niybpkzfotwxowffxpps.supabase.co/storage/v1/object/public/artphotos/Charcoal/cobain.png?t=2024-02-28T22%3A18%3A44.665Z', 'Cobain', 'A charcoal drawing of Kurt Cobain', 'A commissioned drawing of Kurt Cobain.', '18" x 24"', 'Charcoal on paper');
INSERT INTO images (category_id, url, title, description, detaileddesc, size, medium) VALUES
(3, 'https://niybpkzfotwxowffxpps.supabase.co/storage/v1/object/public/artphotos/Charcoal/cybertruck.jpeg', 'Cybertruck', 'An homage to the truck of the future', 'This beaded postcard of Shiprock was made to honor my ancestral homeland.', '4" x 4"', 'Charcoal on paper');
INSERT INTO images (category_id, url, title, description, detaileddesc, size, medium) VALUES
(3, 'https://niybpkzfotwxowffxpps.supabase.co/storage/v1/object/public/artphotos/Charcoal/exhausted.jpg?t=2024-02-28T22%3A19%3A28.376Z', 'Exhausted', 'A beaded "painting" of Utah', 'This piece took 500 hours to create. It represents the spectrum of flora, fauna and cultures within Utah.', '13" x 17"', 'Charcoal and enamel paint on paper');
INSERT INTO images (category_id, url, title, description, detaileddesc, size, medium) VALUES
(3, 'https://niybpkzfotwxowffxpps.supabase.co/storage/v1/object/public/artphotos/Charcoal/johnandexene.JPG?t=2024-02-28T22%3A19%3A39.188Z', 'Vanimal: The Desert Rose', 'A beaded medallion of my old camper van', 'My old Dodge van which I traveled the western US in', '6" x 6"', 'size 13 seed beads');
INSERT INTO images (category_id, url, title, description, detaileddesc, size, medium) VALUES
(3, 'https://niybpkzfotwxowffxpps.supabase.co/storage/v1/object/public/artphotos/Charcoal/medicineman.JPG', 'X Medallion', 'A beaded medallion for Exene Cervenka of X', 'A beaded medallion commissioned for Exene Cervenka of the punk band, X', '6" x 6"', 'size 13 seed beads');
INSERT INTO images (category_id, url, title, description, detaileddesc, size, medium) VALUES
(3, 'https://niybpkzfotwxowffxpps.supabase.co/storage/v1/object/public/artphotos/Charcoal/pump.jpeg', 'Medicine Wheels', 'Beaded medicine wheel pins', 'Beaded medicine wheel pins I made for the Urban Indian Center of Salt Lake City. The pins were given to graduates of their substance abuse program.', '1.5" x 1.5"', 'size 13 seed beads');
INSERT INTO images (category_id, url, title, description, detaileddesc, size, medium) VALUES
(3, 'https://niybpkzfotwxowffxpps.supabase.co/storage/v1/object/public/artphotos/Charcoal/snowcollie.jpg', '45 Revolutions', 'Beaded brooches of 45 RPM adapters', 'These were sold to fundraise for the Native American Music Fund. This organization provides instruments and music lessons to Navajo youth.', '2"x 2"', 'size 13 seed beads');
INSERT INTO images (category_id, url, title, description, detaileddesc, size, medium) VALUES
(3, 'https://niybpkzfotwxowffxpps.supabase.co/storage/v1/object/public/artphotos/Charcoal/weaver.png', 'Flower of Life', 'A beaded cuff and earring set made for a breast cancer survivor', 'The three flowers represent her, her husband and daughter; a triad of strength and resilience.', 'cuff: 2" x 6", earrings: 1.5" x 1.5"', 'size 13 seed beads');