INSERT INTO images (category_id, url, title, description, detaileddesc, size, medium, slug, year) VALUES
(9, 'https://niybpkzfotwxowffxpps.supabase.co/storage/v1/object/public/artphotos/Folk%20Art/backpack.jpg?t=2024-02-29T20%3A45%3A04.759Z', 'Beadings From San Francisco', 'A beaded postcard of the Golden Gate Bridge', 'A block printed greeting card. An homage to my late uncle who was a great poet and juggler. He lived out of a backpack on the streets, but would volunteer at homeless shelters', '5" x 7"', 'block print ink', 'yei-for-joey', 2018),
(9, 'https://niybpkzfotwxowffxpps.supabase.co/storage/v1/object/public/artphotos/Folk%20Art/cigbox.JPG?t=2024-02-29T20%3A45%3A15.233Z', 'Cigar Box Guitars', 'Handmade cigar box guitars for a community education class', 'Cigar box guitars I made for a community education class. I taught several of these workshops where the students assembled and decoupaged their new instrument.', '8" x 24"', 'repurposed cigar boxes, poplar, and metal hardware', 'cigar-box-guitars', 2017),
(9, 'https://niybpkzfotwxowffxpps.supabase.co/storage/v1/object/public/artphotos/Folk%20Art/clashjacket.JPG?t=2024-02-29T20%3A45%3A24.306Z', 'Leather Jacket', 'My junior high leather jacket', 'My leather jacket from junior high. I painted all my favorite punk band logos on it.', NULL, 'leather and acrylic paint', 'leather-jacket', 2002),
(9, 'https://niybpkzfotwxowffxpps.supabase.co/storage/v1/object/public/artphotos/Folk%20Art/diddleygit.jpg?t=2024-02-29T20%3A45%3A33.033Z', 'Tribute to Bo', 'Bo Diddley Cigar Box Guitar', 'A tribute to Bo Diddley', '8" x 24"', 'repurposed cigar box guitar, graphite drawing, acrylic paint, metal hardware', 'tribute-to-bo', 2017),
(9, 'https://niybpkzfotwxowffxpps.supabase.co/storage/v1/object/public/artphotos/Folk%20Art/heartracing.jpg?t=2024-02-29T20%3A45%3A43.241Z', 'Two-Tone Two-Spirit', 'Block printed deer', 'A block printed version of an acrylic painting of mine.', '5" x 7"', 'block print ink', 'two-tone-two-spirit', 2018),
(9, 'https://niybpkzfotwxowffxpps.supabase.co/storage/v1/object/public/artphotos/Folk%20Art/mayhemjacket.jpg?t=2024-02-29T20%3A45%3A50.645Z', 'Metal Mayhem', 'A metalhead leather jacket', 'A leather jacket painted for a metalhead.', NULL, 'leather and acrylic paint', 'metal-mayhem', 2017),
(9, 'https://niybpkzfotwxowffxpps.supabase.co/storage/v1/object/public/artphotos/Folk%20Art/mestizo.JPG?t=2024-02-29T20%3A45%3A59.297Z', 'Mestizo Anniversary', 'A photo collage board for Mestizo Coffee', 'A photo collage board for Mestizo Coffee in Salt Lake City. This was a celebratory piece for their 1 year anniversary', '18" x 24"', 'acrylic paint and photos on wood panel', 'mestizo', 2011),
(9, 'https://niybpkzfotwxowffxpps.supabase.co/storage/v1/object/public/artphotos/Folk%20Art/vanimal.jpg?t=2024-02-29T20%3A46%3A07.385Z', 'Vanimal', 'A block print of my old camper van', 'A block print tribute to my old camper van that I traveled the western U.S. in.', '5" x 7"', 'block print ink', 'vanimal', 2018),
(9, 'https://niybpkzfotwxowffxpps.supabase.co/storage/v1/object/public/artphotos/Folk%20Art/yucca.jpg?t=2024-02-29T20%3A46%3A15.044Z', 'Yucca', 'A block print of a yucca plant', 'A block print of a yucca plant and navajo design. I used this prints to fundraise for art supplies for Navajo youth.', '5" x 7"', 'block print ink', 'yucca', 2018);
